using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using System.Xml.Serialization;

namespace DVBViewerServerApiWrapper.Helper
{
    /// <summary>
    /// Class wich contains dynamics methods to generate a List
    /// </summary>
    internal static class Lists
    {
        /// <summary>
        /// Generates a List of T. So T have to be an object from the <see cref="Model"/> namespace!
        /// </summary>
        /// <typeparam name="T">The list which should be generated.</typeparam>
        /// <param name="page">The page which should be called.</param>
        /// <param name="uriParameters">The UriParameters for the page</param>
        /// <param name="others">Others is an array of classes to be additionally generated by the deserializer.</param>
        /// <returns></returns>
        internal static async Task<T> GetListAsync<T>(string page, List<UriParameter> uriParameters, Type[] others = null)
        {
            //get the current instance of the main Api Class
            var dvbApi = DVBViewerServerApi.GetCurrentInstance();
            if (dvbApi != null)
            {
                //Get the XML-Data from the server
                var xmldata = await dvbApi.GetApiDataAsync(page, uriParameters).ConfigureAwait(false);

                if (xmldata != null)
                {
                    //Deserialize the xml-Data to the objects
                    return Deserializer.Deserialize<T>(xmldata, others);
                }
            }
            return default;
        }
    }
}
